config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'user/index'

  get 'user/new'

  get 'user/create'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  mount Sidekiq::Web => '/sidekiq'

  scope "/admin" do
    resources :users
  end

  root 'weddings#dashboard'

  resources :events
  resources :settings do
    member do
      put :aktifasi
      patch :customtext
    end
    collection do
      get :reset
    end
  end
  resources :displays
  resources :type_of_events
  resources :guests do
  	collection {
    post :import
    get :presence
    get :transfer
    get :gift
    get :print_qr
    get :print_no_undian
  	}
  end

  resources :weddings do
    collection{
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :report_wedding
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      post :import  
    }
  end

  resources :gatherings do
    collection{
      post :import
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      get :pengaturan
      get :reset
    }
  end

  resources :concerts do
    collection{
      post :import
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :report_concert
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      get :pengaturan
      get :reset
    }
  end

  get '/dashboards/coming_soon', to: 'dashboards#coming_soon'
  get '/dashboards', to: 'dashboards#index'

end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :type_of_event
	has_many :guests
	has_many :gatherings, dependent: :destroy
	has_many :concerts, dependent: :destroy
	has_many :guest_temporaries

	def self.search(name)
    name = name ? name.upcase : ""
    where("upper(name) ilike ?", "%#{name}%")
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /events
  # GET /events.json
  def index
    @events = Event.search(params[:name]).page(params[:page]).per(10)
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.date = params[:event][:event_date].to_date
    @event.status = false

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
        format.js { render 'contoh' }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event.date = params[:event][:event_date].to_date
    @event.status = params[:event][:status]
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    DeleteMasterWorker.perform_async(params[:id])
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name,:event_owner,:target_of_guest,:type_of_event_id)
    end

    def generate_date
      d = params.require(:date).permit(:date_event)
      
      return Date.new(d["date_event(1i)"].to_i,d["date_event(2i)"].to_i,d["date_event(3i)"].to_i)
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, class: 'form-horizontal') do |f| %>  
    <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div class="form-group">
    <label class="col-sm-2 control-label">Nama</label>
    <div class="col-sm-10">
      <%= f.text_field :name, class:"form-control form-control-sm", placeholder:"Input nama event" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Tanggal</label>
    <div class="col-sm-10">
      <%= f.text_field :event_date, class:"form-control", id: "date-picker", placeholder:"Pick a date" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Pemilik Event</label>
    <div class="col-sm-10">
      <%= f.text_field :event_owner, class:"form-control form-control-sm", placeholder:"Masukkan nama pemilik event" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Jenis Event</label>
    <div class="col-sm-10">
      <%= f.collection_select( :type_of_event_id, TypeOfEvent.all, :id, :name, {:include_blank => true}, {:class => 'form-control select2'}) %>
    </div>
  </div>
  

  <div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <div class="col-sm-10">
      <%= link_to 'Kembali',events_path, class: 'btn btn-danger' %>
      <%= f.submit class: 'btn btn-success' %>
    </div>
  </div>

  <% end %>

app/views/events/contoh.js.erb
alert('tes')

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Form Edit Event</h3><br>
    Edit event
  </div>
<%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> Events 
      <%= link_to 'New Event', new_event_path, class:"btn btn-primary btn-sm pull-right"%></h3>
  </div><br>

  <%= form_tag events_path, method: "GET" do %>
    <% 5.times do %>
      <div class="col-sm-2"></div>
    <% end %>
    <div class="col-sm-2">
      <%= text_field_tag :name, params[:name], class: "form-control form-control-sm", placeholder: "Search" %>
    </div>
  <% end %><br>

  <div class="panel-body">
    <table class="table table-hovered table-bordered margin10">
      <thead class="thead-default">
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Event Owner</th>
          <th>Status</th>
          <th>Type Event Id</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
      <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.date %></td>
            <td><%= event.event_owner %></td>
            <td><%= event.status %></td>
            <td><%= event.type_of_event.name %></td>
            <td>
              <div class="btn-group" role="group" aria-label="...">
                <%= link_to 'Edit', edit_event_path(event),{class:"btn btn-success btn-sm"} %></button>
                <button type="button" class="btn btn-delete btn-sm" onclick="button_delete(<%= event.id %>)">Delete</button>
              </div>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @events %>
  </div>
</div>

<script type="text/javascript">
  let button_delete = (id)=>{
    if(confirm('Are u sure want to delete that event?')){
      $.ajax({
        url:"/events/"+id,
        method:'DELETE'
      }).done( () => window.location.href = "/events");
    }
  }
</script>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Event Baru</h3>
  </div>

  <div class="panel-body">
    <%= render 'form', event: @event %>
  </div>
</div>

app/views/events/show.html.erb
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>