config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'user/index'

  get 'user/new'

  get 'user/create'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  mount Sidekiq::Web => '/sidekiq'

  scope "/admin" do
    resources :users
  end

  root 'weddings#dashboard'

  resources :events
  resources :settings do
    member do
      put :aktifasi
      patch :customtext
    end
    collection do
      get :reset
    end
  end
  resources :displays
  resources :type_of_events
  resources :guests do
  	collection {
    post :import
    get :presence
    get :transfer
    get :gift
    get :print_qr
    get :print_no_undian
  	}
  end

  resources :weddings do
    collection{
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :report_wedding
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      post :import  
    }
  end

  resources :gatherings do
    collection{
      post :import
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      get :pengaturan
      get :reset
    }
  end

  resources :concerts do
    collection{
      post :import
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :report_concert
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      get :pengaturan
      get :reset
    }
  end

  get '/dashboards/coming_soon', to: 'dashboards#coming_soon'
  get '/dashboards', to: 'dashboards#index'

end

app/models/setting.rb
class Setting < ApplicationRecord
	has_many :displays
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  skip_before_action :verify_authenticity_token
  include SettingsHelper

  def index
    @event_active = Event.where('status = true').first
    @events = Event.where('status = false').order(:name)
    @setting = Setting.first
    @check_box_settings = Setting.first
    @display = Display.joins(:setting).first
  end

  def aktifasi
    @event = Event.find(params[:id])
    @event_lama = Event.where('status = true')
    ActiveRecord::Base.transaction do
      @event_lama.update(status:false)
      @event.update(status:true)
    end
    redirect_to settings_path, notice: 'Event berhasil diupdate'
  end

  def update
    @setting = Setting.find(1)
    begin
      if params[:no_print].present?
        @setting.update_attributes(
          no_undian:false,
          nama_meja:false,
          nama_undangan:false,
          jumlah_souvenir:false,
          nama_angpao:false
        )
      else
        @setting.update_attributes(
          no_undian:params[:setting][:no_undian].present? ? true : false,
          nama_meja:params[:setting][:nama_meja].present? ? true : false,
          nama_undangan:params[:setting][:nama_undangan].present? ? true : false,
          jumlah_souvenir:params[:setting][:jumlah_souvenir].present? ? true : false,
          nama_angpao:params[:setting][:nama_angpao].present? ? true : false,
          custom_one_text:params[:setting][:custom_one_text].present? ? params[:setting][:custom_one_text] : nil 
        )
      end
      @con = true
      respond_to do |format|
        format.js { render 'settings/index' }
      end
      
    rescue
      @con = false
      respond_to do |format|
        format.js { render 'settings/index' }
      end
    end
  
  end

  def customtext
    @setting = Setting.find(1)
    if @setting.update(customtext_params)
      # Guest.joins(:event).where("events.status = true").update(guest_params)
      redirect_to settings_path, notice: 'Currency was successfuly edited.'
    end
  end

  def reset
    event_id = Event.find_by(status: true).id
    guest = Gathering.where(event_id: event_id)
    guest.update_all(:presence => false, :time_of_entry => nil,:ticket => false, :time_of_get_ticket => nil)
  end

  private

  def customtext_params
    params.require(:setting).permit(:custom_one_text,:custom_two_text,:custom_three_text,:custom_four_text,:custom_five_text)
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form_custom_text.html.erb
<% if @setting.custom_one == false && @setting.custom_two == false && @setting.custom_three == false && @setting.custom_four == false && @setting.custom_five == false %>
  <div></div>
<% else %>
  <h4>Custom Field Title</h4>
  <hr>
<% end %>
  <%= form_for @setting, url: customtext_setting_path(@setting), :html => {:class => 'form-horizontal'} do |f| %>
    <% if @setting.custom_one == true %>
      <div class="form-group">
        <label class="col-sm-2 control-label">Custom One</label>
        <div class="col-sm-10">
          <%= f.text_field :custom_one_text, class:"form-control", placeholder:"Input custom field title" %>
        </div>
      </div>
    <% end %>

    <% if @setting.custom_two == true %>
      <div class="form-group">
        <label class="col-sm-2 control-label">Custom Two</label>
        <div class="col-sm-10">
          <%= f.text_field :custom_two_text, class:"form-control form-control-sm", placeholder:"Input custom field title" %>
        </div>
      </div>
    <% end %>

    <% if @setting.custom_three == true %>
      <div class="form-group">
        <label class="col-sm-2 control-label">Custom Three</label>
        <div class="col-sm-10">
          <%= f.text_field :custom_three_text, class:"form-control form-control-sm", placeholder:"Input custom field title" %>
        </div>
      </div>
    <% end %>

    <% if @setting.custom_four == true %>
      <div class="form-group">
        <label class="col-sm-2 control-label">Custom Four</label>
        <div class="col-sm-10">
          <%= f.text_field :custom_four_text, class:"form-control form-control-sm", placeholder:"Input custom field title" %>
        </div>
      </div>
    <% end %>

    <% if @setting.custom_five == true %>
      <div class="form-group">
        <label class="col-sm-2 control-label">Custom Five</label>
        <div class="col-sm-10">
          <%= f.text_field :custom_five_text, class:"form-control form-control-sm", placeholder:"Input custom field title" %>
        </div>
      </div>
    <% end %>

    <% if @setting.custom_one == false && @setting.custom_two == false && @setting.custom_three == false && @setting.custom_four == false && @setting.custom_five == false %>
      <div></div>
    <% else %>
      <div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
          <%= f.submit 'Simpan', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  <% end %>

app/views/settings/copy.html.erb
<div class="panel panel-default">
  
  <div class="panel-heading">
    <h3 class="panel-title">
      Settings
      <%= button_tag 'Reset', class: 'btn btn-danger btn-sm pull-right', id: 'reset' %>
    </h3>    
  </div>

  <div class="panel-body">
    
    <h4>Aktifasi Event</h4>
    <hr>
    <div class="alert alert-info">
      <% if @event_active.present? %>
        Event yang sedang aktif : <strong><%= @event_active.name.present? ? @event_active.name : '' %></strong>
      <% end %>
    </div>

    <table class="table table-hovered table-bordered margin10">
      <thead class="thead-default">
        <tr>
          <th>Nama</th>
          <th>Tanggal</th>
          <th>Pemilik Event</th>
          <th>Jenis</th>
          <th>#</th>
        </tr>
      </thead>
      <tbody>
      <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.date %></td>
            <td><%= event.event_owner %></td>
            <td><%= event.type_of_event.name %></td>
            <td><%= link_to 'Aktifkan', aktifasi_setting_path(event.id), method: :put, class:'btn btn-success' %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <div class="row">
      <div class="col-lg-3 col-sm-4 col-6">
        <div class="groups__item">
          <h4>Pengaturan Cetak</h4>
          <hr>
            <%= form_for(@setting) do |f| %>
              <div class="checkbox">
                <label>
                  <%= f.check_box :no_undian %> No Undian
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <%= f.check_box :nama_meja %> Nama Meja
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <%= f.check_box :nama_undangan %> Nama Undangan / Angpau
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <%= f.check_box :custom_one %> <%= @setting.custom_one_text if @setting.custom_one_text.present? %> (Custom One)
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <%= f.check_box :custom_two %> <%= @setting.custom_two_text if @setting.custom_two_text.present? %> (Custom Two)</strong>
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <%= f.check_box :custom_three %> <%= @setting.custom_three_text if @setting.custom_three_text.present? %> (Custom Three)</strong>
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <%= f.check_box :custom_four %> <%= @setting.custom_four_text if @setting.custom_four_text.present? %> (Custom Four)
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <%= f.check_box :custom_five %> <%= @setting.custom_five_text if @setting.custom_five_text.present? %> (Custom Five)
                </label>
              </div>
              <%= f.submit 'Simpan', class: 'btn btn-primary' %>
            <% end %>
        </div>
      </div>

      <div class="col-lg-9 col-sm-12">
        <%= render 'form_custom_text.html.erb' %>    
      </div>
    </div>

    <div class="row">


      <div class="wrap">
        
        <input type="hidden" value="<%= @setting.id %>" />
        <div class="tile"> 
          <img src='https://images.unsplash.com/photo-1464054313797-e27fb58e90a9?dpr=1&auto=format&crop=entropy&fit=crop&w=1500&h=996&q=80'/>
          <div class="text">
            
            <h1>PAKET CETAK 1</h1>
            <p class="animate-text"> NO UNDIAN </p>
            <p class="animate-text"> NAMA MEJA </p>
            <p class="animate-text"> NAMA UNDANGAN </p>
            <p class="animate-text"> JUMLAH SOUVENIR </p>
            <p class="animate-text"> NAMA ANGPAO </p>
          </div>
        </div>

        <div class="tile"> 
          <img src='https://images.unsplash.com/photo-1458668383970-8ddd3927deed?dpr=1&auto=format&crop=entropy&fit=crop&w=1500&h=1004&q=80'/>
          <div class="text">
            <h1>PAKET CETAK 2</h1>
            <p class="animate-text"> NAMA MEJA </p>
            <p class="animate-text"> JUMLAH SOUVENIR </p>
            <p class="animate-text"> NAMA ANGPAO </p>
          </div>
        </div>
        
        <div class="tile"> 
          <img src='https://images.unsplash.com/photo-1422393462206-207b0fbd8d6b?dpr=1&auto=format&crop=entropy&fit=crop&w=1500&h=1000&q=80'/>
          <div class="text">
            <h1>PAKET CETAK 3</h1>
            <p class="animate-text">NAMA MEJA</p>
            <p class="animate-text">JUMLAH SOUVENIR</p>
          </div>
        </div>

        <div class="tile"> 
          <img src='https://images.unsplash.com/photo-1422393462206-207b0fbd8d6b?dpr=1&auto=format&crop=entropy&fit=crop&w=1500&h=1000&q=80'/>
          <div class="text">
            <h1>PAKET CETAK 3</h1>
            <p class="animate-text">NAMA MEJA</p>
          </div>
        </div>

        <div class="tile"> 
          <img src='https://images.unsplash.com/photo-1422393462206-207b0fbd8d6b?dpr=1&auto=format&crop=entropy&fit=crop&w=1500&h=1000&q=80'/>
          <div class="text">
            <h1>PAKET CETAK 3</h1>
            <p class="animate-text">NAMA ANGPAO</p>
          </div>
        </div>

        <div class="tile"> 
          <img src='https://images.unsplash.com/photo-1422393462206-207b0fbd8d6b?dpr=1&auto=format&crop=entropy&fit=crop&w=1500&h=1000&q=80'/>
          <div class="text">
            <h1>PAKET CETAK 3</h1>
            <p class="animate-text">NAMA SOUVENIR</p>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>
  
</div>

<script>
  $(".wrap .tile .text").click(function(){
    console.log($(this).find("p"));
  //  $.ajax({
  //    url: '/settings/'+$(".wrap input").val(),
  //    method: 'PUT',
  //    data:{ setting:
  //     {
  //       no_undian:  ,
  //       nama_meja,
  //       nama_undangan,
  //       custom_one,
  //       custom_two,
  //       custom_three,
  //       custom_four,
  //       custom_five
  //     } 
  //    }
  //  });
  });
</script>

app/views/settings/index.html.erb
<div class="panel panel-default">
  <div id="infoAlert"></div>
  <div class="panel-heading">
    <h3 class="panel-title">
      Settings
      <%= button_tag 'No Print', class: 'btn btn-primary btn-sm pull-right', onclick: "handleNoPrint(#{@setting.id})" %>
      <%= button_tag 'Reset', class: 'btn btn-danger btn-sm pull-right', id: 'reset', onclick: "handleReset()" %>
    </h3>    
  </div>
  <div class="panel-body">
    <h4>Aktifasi Event</h4>
    <hr>
    <div class="alert alert-info">
      <% if @event_active.present? %>
        Event yang sedang aktif : <strong><%= @event_active.name.present? ? @event_active.name : '' %></strong>
      <% end %>
    </div>
    <table class="table table-hovered table-bordered margin10">
      <thead class="thead-default">
        <tr>
          <th>Nama</th>
          <th>Tanggal</th>
          <th>Pemilik Event</th>
          <th>Jenis</th>
          <th>#</th>
        </tr>
      </thead>
      <tbody>
      <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.date %></td>
            <td><%= event.event_owner %></td>
            <td><%= event.type_of_event.name %></td>
            <td><%= link_to 'Aktifkan', aktifasi_setting_path(event.id), method: :put, class:'btn btn-success' %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <%= form_for(@setting, remote:true) do |f| %>
      <div class="form-group">
        <%= f.label "Title" %>
        <%= f.text_field :custom_one_text,{class:"form-control"} %> <br />
      </div>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>

    <%= form_for(@check_box_settings, remote:true) do |f| %>
      <div class="form-check">
        <%= f.check_box :no_undian, {class:"form-check-input"}, true, false %>
        <%= f.label :no_undian, {class:"form-check-label"} %>
      </div>
      <div class="form-check">            
        <%= f.check_box :nama_meja, {class:"form-check-input"}, true, false %>
        <%= f.label :nama_meja, {class:"form-check-label"} %>
      </div>
      <div class="form-check">
        <%= f.check_box :nama_undangan, {class:"form-check-input"}, true, false %>
        <%= f.label :nama_undangan, {class:"form-check-label"} %>
      </div>
      <div class="form-check">
        <%= f.check_box :jumlah_souvenir, {class:"form-check-input"}, true, false %>
        <%= f.label :jumlah_souvenir, {class:"form-check-label"} %>
      </div>
      <div class="form-group">
        <%= f.check_box :nama_angpao, {class:"form-check-input"}, true, false %>
        <%= f.label :nama_angpao,{class:"form-check-label"} %>
      </div>
      
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
    
    <%= form_for(@display, remote:true) do |f| %>
      <div class="form-group">
        <%= f.check_box :nama, {class:"form-check-input"}, true, false %>
        <%= f.label :nama,{class:"form-check-label"} %>
      </div>
      <div class="form-group">  
        <%= f.check_box :alamat, {class:"form-check-input"}, true, false %>
        <%= f.label :alamat, {class:"form-check-label"}  %>
      </div>
      <div class="form-group">
        <%= f.check_box :nomor_ponsel, {class:"form-check-input"}, true, false %>
        <%= f.label :nomor_ponsel,{class:"form-check-label"} %>
      </div>
      <div class="form-group">
        <%= f.check_box :kategori,{class:"form-check-input"}, true, false %>
        <%= f.label :kategori,{class:"form-check-label"}  %>
      </div>
      <div class="form-group">
        <%= f.check_box :status, {class:"form-check-input"}, true, false %>
        <%= f.label :status,{class:"form-check-label"} %>
      </div>
      <div class="form-group">
        <%= f.check_box :nama_meja, {class:"form-check-input"}, true, false %>
        <%= f.label :nama_meja,{class:"form-check-label"} %>
      </div>
      <div class="form-group">
        <%= f.check_box :guest_id, {class:"form-check-input"}, true, false %>
        <%= f.label :guest_id,{class:"form-check-label"} %>
      </div>
      <div class="form-group">
        <%= f.check_box :souvenir, {class:"form-check-input"}, true, false %>
        <%= f.label :souvenir, {class:"form-check-label"} %>
      </div>
      <div class="form-group">  
        <%= f.check_box :jumlah_souvenir, {class:"form-check-input"}, true, false %>
        <%= f.label :jumlah_souvenir, {class:"form-check-label"} %>
      </div>
      <div class="form-group">
        <%= f.check_box :nama_angpao, {class:"form-check-input"}, true, false %>
        <%= f.label :nama_angpao, {class:"form-check-label"} %>
      </div>
      <div class="form-group">  
        <%= f.check_box :no_undian, {class:"form-check-input"}, true, false %>
        <%= f.label :no_undian,{class:"form-check-label"}  %>
      </div>
      <div class="form-group">
        <%= f.check_box :jumlah_undangan, {class:"form-check-input"}, true, false %>
        <%= f.label :jumlah_undangan,{class:"form-check-label"} %>
      </div>
      <div class="form-group">  
        <%= f.check_box :jabatan, {class:"form-check-input"}, true, false %>
        <%= f.label :jabatan,{class:"form-check-label"} %>
      </div>
      
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  
  
  </div>
</div>
<script>

  let handleNoPrint = (id) => {
     $.ajax({
      url: '/settings/'+id,
      method: 'PUT',
      data: { no_print: true }
    })   
  }

  $(".one .tile .text").click(function(){
    let data = {};
    $(this).find("p").each(function(){
      handleStructureObjectData($(this).attr("id"),data)
    });

    $.ajax({
      url: '/settings/'+ $(".one").find("input").val(),
      method: 'PUT',
      data: { data }
    })
  });

  $(".two .tile .text").click(function(){
    let data = {};
    
    $(this).find("p").each(function(){
      handleStructureObjectData($(this).attr("id"),data)
    });

    $.ajax({
      url: '/settings/'+ $(".one").find("input").val(),
      method: 'PUT',
      data: { data }
    })    
  
  });

  let handleReset= () =>{
    if(confirm('Are u sure want to reset?')){
      $.ajax({
        url:'/settings/reset',
        method:'GET'
      }).done( () => toastr['info']('Reset Successfull'));
    }
  }


  function handleStructureObjectData(obj,data){
    if (obj == 1){ data.no_undian = true }
    if (obj == 2){ data.nama_meja = true }
    if (obj == 3){ data.nama_undangan = true }
    if (obj == 4){ data.jumlah_souvenir = true }
    if (obj == 5){ data.nama_angpao = true } 
  }
</script>

app/views/settings/index.js.erb
<% if @con  %>
  toastr['info']('Update Successfull')
<% else %>
  toastr['error']('There something wrong !!!')
<% end %>