config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'user/index'

  get 'user/new'

  get 'user/create'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  mount Sidekiq::Web => '/sidekiq'

  scope "/admin" do
    resources :users
  end

  root 'weddings#dashboard'

  resources :events
  resources :settings do
    member do
      put :aktifasi
      patch :customtext
    end
    collection do
      get :reset
    end
  end
  resources :displays
  resources :type_of_events
  resources :guests do
  	collection {
    post :import
    get :presence
    get :transfer
    get :gift
    get :print_qr
    get :print_no_undian
  	}
  end

  resources :weddings do
    collection{
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :report_wedding
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      post :import  
    }
  end

  resources :gatherings do
    collection{
      post :import
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      get :pengaturan
      get :reset
    }
  end

  resources :concerts do
    collection{
      post :import
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :report_concert
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      get :pengaturan
      get :reset
    }
  end

  get '/dashboards/coming_soon', to: 'dashboards#coming_soon'
  get '/dashboards', to: 'dashboards#index'

end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  include PresencesHelper
  
  def import
    authorize! :create, Guest
    result = Guest.import(params[:file],params[:guest][:event_id])
    @r = 0 if result == false
    respond_to do |f|
      f.js 
    end
  end

  def index
    render layout: 'presence'
  end

  def new
    if params[:search].present?
      data = JSON.parse(params[:search])["data_search"]
      if data["data"] == "all"
        @weddings = Guest.joins(event: :type_of_event).where("type_of_events.id = 1").where("type_of_events.name ilike '%Wedding%'").where("events.status = TRUE")
                      .order(nama: :asc)
                      .page(params[:page]).per(100)
      else
        @weddings = search(data["name"],data["alamat"],data["kategori"])
      end
      respond_to do |f|
        f.js
      end
    else
      @weddings = Guest.joins(event: :type_of_event).where("type_of_events.id = 1").where("type_of_events.name ilike '%Wedding%'").where("events.status = TRUE")
                      .order(nama: :asc)
                      .page(params[:page]).per(100)
      respond_to do |f|
        f.js
        f.html
      end
    end
  end

  def print
    render layout: false
  end

  def template_qr
    render layout: false
  end

  def template_qr_master
    render layout: false
    @find_guest = Guest.where(guest_id: params[:guest_id])
  end

  def print_qr
    if params[:guest_qr].present?
      find_guest = Guest.where("nama ilike '%#{params[:guest_qr]}%'").limit(1)
      @qrcode = find_guest.first.guest_id.to_s
    end

    ScanWorker.perform_async(find_guest.first.guest_id)

    respond_to do |format|
      format.js { render 'weddings/print_qr' }
    end
  end

  def print_qr_master
    if params[:guest_id].present?
      @find_guest = params[:guest_id]
    end

    respond_to do |format|
      format.js { render 'weddings/print_qr_master' }
    end
  end

  def update_presence
    @find_guest = Guest.where(guest_id: params[:guest_code])
    @display = Display.find(1)
    if @find_guest.present? && @find_guest.first.presence != true
      setting = Setting.where(id:@find_guest.first.event_id)
      @settingan = Setting.last
      @print = {}
      ScanWorker.perform_async(params[:guest_code])
      
      @display = Display.find(1)      

      @dis_array = []
      i = 1
       
      while i <= 13  do
        @dis_array.push("alamat") if i==1 && @display.alamat == true  
        @dis_array.push("nomor_ponsel") if i==2 && @display.nomor_ponsel == true  
        @dis_array.push("kategori") if i==3 && @display.kategori == true  
        @dis_array.push("status") if i==4 && @display.status == true  

        @dis_array.push("nama_meja") if i==5 && @display.nama_meja == true  
        @dis_array.push("guest_id") if i==6 && @display.guest_id == true  
        @dis_array.push("souvenir") if i==7 && @display.souvenir == true  
        @dis_array.push("jumlah_souvenir") if i==8 && @display.jumlah_souvenir == true  

        @dis_array.push("nama_angpao") if i==9 && @display.nama_angpao == true  
        @dis_array.push("no_undian") if i==10 && @display.no_undian == true 
        @dis_array.push("jumlah_undangan") if i==11 && @display.jumlah_undangan == true 
        @dis_array.push("jabatan") if i==12 && @display.jabatan == true 
        i += 1
      end


      respond_to do |format|
        format.js { render 'weddings/update_presence' }
      end
    else
      @presence = if @find_guest.first.presence == true
        true
      else
        false
      end
      respond_to do |format|
        format.js { render 'weddings/index' }
      end
    end
  end

  def printulang
    render layout: 'presence'
  end

  def reprint
    @find_guest = Guest.where(guest_id: params[:guest_code])

    if @find_guest.present? && @find_guest.first.presence == TRUE
      setting = Setting.where(id:@find_guest.first.event_id)
      @print = {}
      respond_to do |format|
        format.js { render 'weddings/reprint' }
      end
    else
      respond_to do |format|
        format.js { render 'weddings/index' }
      end
    end
  end

  def create
    guest = Guest.new
    guest.name = params[:name]
    guest.city = params[:kota]
    guest.address = params[:address]
    guest.telephone = params[:telephone]
    guest.category = params[:category]
    guest.event_id = Event.joins(:type_of_event)
                          .where(status:true)
                          .where("type_of_events.id = 1")
                          .where("type_of_events.name ilike '%Wedding%'").first.id
    # guest.amount_of_present = params[:amount_of_present]
    guest.type_of_guest = params[:type_of_guest]
    guest.presence = true
    guest.nama_meja = params[:nama_meja]
    # guest.no_undian =  rand.to_s.slice(2,5)
    guest.time_of_entry = Time.now()
    guest.guest_id = Guest.generate_number(guest.name)
    guest.save
    respond_to do |format|
      format.html { redirect_to new_wedding_path }
      format.js
    end
  end

  def souvenir
    render layout: 'presence'
  end

  def update_souvenir
    @find_guest = Guest.where(guest_id: params[:souvenir])
    if @find_guest.present? && @find_guest.first.souvenir != TRUE
      @souvenir = 'Sukses'
      SouvenirWorker.perform_async(params[:souvenir])
    elsif @find_guest.present? && @find_guest.first.souvenir == TRUE
      @souvenir = 'Sudah'
    elsif @find_guest.blank?
      @souvenir = 'Gagal'
    end

    respond_to do |format|
      format.js { render 'weddings/index' }
    end
  end

  def print_qr_page
    render layout: 'presence'
  end

  def update_print_qr_page
  end

  def dashboard
    content = {}
    @total_guest = Guest.joins(:event).where("events.status=true").count
    @guest_sudah_hadir = Guest.joins(:event).where("events.status=true").where("guests.presence=true").count
    @guest_belum_hadir = Guest.joins(:event).where("events.status=true").where("guests.presence=false").count
    @jumlah_souvenir = Guest.joins(:event).where("events.status=true").where("guests.souvenir=true").count
  end

  def report
    @setting = Setting.first
    @events = TypeOfEvent.joins(:events).where(name:"Wedding").select("events.name as name,events.id as id")
    @jenis_kategori = delete_duplicate_value(Guest.select(:kategori))
    if params[:event_id].present? && params[:jenis_kategori] == 'all'
      query = "event_id = #{params[:event_id]}"
    elsif params[:event_id].present? && params[:jenis_kategori] != 'all'
      query = "event_id = #{params[:event_id]} AND category ilike '%#{params[:jenis_kategori]}%'"
    end
    @guests = Guest.where(query)

    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def report_wedding
    unless params[:event].nil?
      if params[:jenis_kategori].present?
        data_hadir = Guest.joins(:event)
                           .where("events.name like '%#{params[:event][:event_id]}%'")
                          .where(presence:true)
        data_tidak_hadir = Guest.joins(:event)
                                .where("events.name like '%#{params[:event][:event_id]}%'")
                                .where('guests.presence = false or guests.presence = null')
        @report = tentukan_jenis_report(params[:jenis_kategori],data_hadir,data_tidak_hadir,params[:presence_kategori])
      end

      @no = if params[:page].to_i == 1 || params[:page].blank?
        1
      else
        (params[:page].to_i * 100) - 100 + 1
      end

      respond_to do |format|
        format.js { render '/weddings/report_wedding' }
      end
    else
      @jenis_kategori = delete_duplicate_value(Guest.select(:category))
    end
  end

  def export_excel
    @custom_header = Setting.all
    @exports= Guest.joins(:event).where("events.name like '%#{params[:event]}%'")
    respond_to do |format|
      format.xls
    end
  end

end

app/views/weddings/_already.html.erb
<%= render 'already-svg' %>
<div class="result-text">
  <p><span class="name"><%= @find_guest[0].nama %> sudah hadir</span></p>
  <%= link_to reprint_weddings_path(guest_code: @find_guest[0].guest_id), remote: true do %>
    <%= image_tag('print.ico', style: 'width:70px; height: auto;', title: 'Print Ulang') %>
  <% end %>
</div>

app/views/weddings/_hadir.html.erb
<%= render 'hadir-svg' %>

  <div class="active-wedding">
    <h4 style="padding-top:18px;"><span class="active-wedding-name">Welcome</span></h4>
    <p><span class="active-wedding-name" style="font-size: 58px !important;"><%= @find_guest[0].nama %></span></p>
    <br/>
  </div>
  
  <div> 
    <% if @display.nomor_ponsel == true &&
          @display.alamat == true &&
          @display.kategori == true &&
          @display.status == true &&
          @display.nama_meja == true &&
          @display.souvenir == true &&
          @display.jumlah_souvenir == true &&
          @display.nama_angpao == true &&
          @display.no_undian == true &&
          @display.guest_id == true &&
          @display.jabatan == true &&
          @display.jumlah_undangan == true            
    %>
        <span class="display-guest-id"><%= @find_guest[0].guest_id %></span>   
        <span class="display-nomor-ponsel"><%= @find_guest[0].nomor_ponsel %></span>
        <span class="display-alamat"><%= @find_guest[0].alamat %></span><br />

        <span class="display-kategori"><%= @find_guest[0].kategori %></span>      
        <span class="display-status"><%= @find_guest[0].status %></span>   
        <span class="display-nama-meja"><%= @find_guest[0].nama_meja %></span><br />
        
        <span class="display-souvenir"><%= @find_guest[0].souvenir %></span>   
        <span class="display-jumlah-souvenir"><%= @find_guest[0].jumlah_souvenir %></span>
        <span class="display-nama-angpao"><%= @find_guest[0].nama_angpao %></span><br />   
        
        <span class="display-nomor-undian"><%= @find_guest[0].no_undian %></span>
        <span class="display-jabatan"><%= @find_guest[0].jabatan %></span>   
        <span class="display-jumlah-undangan"><%= @find_guest[0].jumlah_undangan %></span><br />        
    <% else %>

      <div class="result" >
        <% if @dis_array.count > 5 %>
            <% j = 0 %>

            <% for i in 1..@dis_array.count do %>
              <% if i % 4 == 0 %>
                  <% if j == 0 %>
                    <span class="display-guest-id"><%= @find_guest[0].guest_id %></span> <br />
                  <% end %> 

                  <% if j == 1 %>
                    <span class="display-kategori"><%= @find_guest[0].guest_id %></span> <br />
                  <% end %>
                  
                  <% if j == 2 %>
                    <span class="display-nomor-undian"><%= @find_guest[0].guest_id %></span> <br /> 
                  <% end %>

                <% j+=1 %>
              <% else %>

                  <% if j == 0 %>
                    <span class="display-guest-id"><%= @find_guest[0].guest_id %></span>
                  <% end %> 

                  <% if j == 1 %>
                    <span class="display-kategori"><%= @find_guest[0].guest_id %></span>
                  <% end %>
                  
                  <% if j == 2 %>
                    <span class="display-nomor-undian"><%= @find_guest[0].guest_id %></span>
                  <% end %>
                  
              <% end %>
            <% end %>

           
        <% else %>

          <% if @display.nomor_ponsel == true %>
            <p><span class="category"><%= @find_guest[0].nomor_ponsel %></span></p>
          <% end %>
          
          <% if @display.alamat == true %>
            <p><span class="category"><%= @find_guest[0].alamat %></span></p>
          <% end %>
          
          <% if @display.kategori == true %>
            <p><span class="category"><%= @find_guest[0].kategori %></span></p>
          <% end %>

          <% if @display.status == true %>
            <p><span class="category"><%= @find_guest[0].status %></span></p>
          <% end %>
          
          <% if @display.nama_meja == true %>
            <p><span class="category"><%= @find_guest[0].nama_meja%></span></p>
          <% end %>
          
          <% if @display.nama_angpao == true %>
            <p><span class="category"><%= @find_guest[0].nama_angpao %></span></p>
          <% end %>

           <% if @display.no_undian == true %>
            <p><span class="category"><%= @find_guest[0].no_undian %></span></p>
          <% end %>

           <% if @display.guest_id == true %>
            <p><span class="category"><%= @find_guest[0].guest_id %></span></p>
          <% end %>

           <% if @display.jabatan == true %>
            <p><span class="category"><%= @find_guest[0].jabatan %></span></p>
          <% end %>

           <% if @display.jumlah_undangan == true %>
            <p><span class="category"><%= @find_guest[0].jumlah_undangan %></span></p>
          <% end %>        

        <% end  %>

      </div>

    <% end %>
  </div>
  

app/views/weddings/_list_report.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      Event
      <%= link_to 'Export Excel',  '' ,id:'export_wedding', class:"btn btn-primary btn-sm pull-right"%>
    </h3>
  </div>
  <div class="panel-body">
    <% if @report.present? %>
      <div class="col-sm-2">
        <h4>
          <div class="alert alert-info">
            Total Undagan: <%= @report[:data_hadir].to_i + @report[:tidak_hadir].to_i %>
          </div>
        </h4>
      </div>
      <div class="col-sm-2">
        <h4>
          <div class="alert alert-success">
            Hadir: <%= @report[:data_hadir].to_i  %>
          </div>
        </h4>
      </div>
      <div class="col-sm-2">
        <h4>
          <div class="alert alert-danger">
            Tidak Hadir: <%= @report[:tidak_hadir].to_i  %>
          </div>
        </h4>
      </div>
      <hr>
      <%= render 'weddings/list_report/list_report_special_case' %>
      <%= paginate @report[:report] %>
    <%else%>
      <div class="col-sm-12">
        <h4>
          <div class="alert alert-info">
            Data Tidak Ada
          </div>
        </h4>
      </div>
    <% end %>
  </div>
</div>
<script><%= render "weddings/js/list_report.js"; %></script>

app/views/weddings/_souvenir_hadir.html.erb
<%= render 'hadir-svg' %>
<div class="result-text">
  <% if @find_guest[0].guest_id != nil %><p><span class="category"><%= @find_guest[0].guest_id %></span></p><% end %>
  <p><span class="name"><%= @find_guest[0].nama %></span></p>
  <% if @find_guest[0].address != nil %><p><span class="address"><%= @find_guest[0].address %></span></p><% end %>
  <p><span class="name">Souvenir : <%= @find_guest[0].jumlah_souvenir %></span></p>
</div>

app/views/weddings/_souvenir_non_hadir.html.erb
<%= render 'already-svg' %>
<div class="result-text">
  <p><span class="name">Souvenir Telah Diambil</span></p>
</div>

app/views/weddings/_souvenir_not_found.html.erb
<%= render 'already-svg' %>
<div class="result-text">
  <p><span class="name">ID tidak terdaftar</span></p>
</div>

app/views/weddings/_tolak.html.erb
<%= render 'already-svg' %>
<div class="result-text">
  <p><span class="name">ID tidak terdaftar</span></p>
</div>

app/views/weddings/index.js.erb
<% if @presence == TRUE %>
  $("#notice").html("<%= escape_javascript(render 'already') %>")
<% elsif @presence == FALSE %>
  $("#notice").html("<%= escape_javascript(render 'tolak') %>")
<% elsif @souvenir == 'Sukses'  %>
  $("#notice").html("<%= escape_javascript(render 'souvenir_hadir') %>")
<% elsif @souvenir == 'Sudah' %>
  $("#notice").html("<%= escape_javascript(render 'souvenir_non_hadir') %>")
<% elsif @souvenir == 'Gagal' %>
  $("#notice").html("<%= escape_javascript(render 'souvenir_not_found') %>")
<% end %>

app/views/weddings/report.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      Report Wedding
    </h3>
  </div>
  <div class="panel-body">
    <%= form_tag  report_weddings_path, method: "GET", class: 'form-horizontal' do %>
      <div class="form-group">
        <label class="col-sm-2 control-label">Pilih Event</label>
        <div class="col-sm-10">
          <select name="event_id" class="form-control">
            <% @events.each do |event| %>
              <option value="<%= event.id %>"><%= event.name %></option>
            <% end %>
          </select>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Kategori</label>
        <div class="col-sm-10" id="jenis_kategori">
          <select class="form-control select2" name="jenis_kategori">
            <option value="all">Semua</option>
            <% @jenis_kategori.each do |jk| %>
              <option value="<%= jk %>"><%= jk %></option>
            <% end %>
          </select>
        </div>
      </div>
      <!--
      <div class="form-group">
        <label class="col-sm-2 control-label">Kategori</label>
        <div class="col-sm-10" id="jenis_kategori">
          <select class="form-control select2" name="presence">
            <option value="all">Semua</option>
            <option value="hadir">Hadir</option>
            <option value="tidak_hadir">Tidak Hadir</option>
          </select>
        </div>
      </div>
      -->
      <div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
          <%= submit_tag 'Submit', class: 'btn btn-success' %>
        </div>
      </div>
    <% end %>
  </div>
</div>


<% if params[:event_id].present? %>
  <%= link_to 'Download as .xlsx', report_weddings_path(format: :xlsx, event_id: params[:event_id], jenis_kategori: params[:jenis_kategori]) %>
<% end %>

app/views/weddings/report_wedding.js.erb
$("#list_report").html("<%= escape_javascript(render 'list_report') %>");

app/views/weddings/template_qr_master.html.erb
<!DOCTYPE html>
<html lang="en" moznomarginboxes mozdisallowselectionprint>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <style>
    @media print {
      @page { margin: 0; }
      body { margin: 0.5cm; }
    }
  </style>
</head>
<body>
    <table style="width: 100%; text-align: center;" >
        <tbody>
          <tr>
            <td><img src="<%= generate_qr(params[:guest_id]) %>" class: "qr-code" style="width:50%;"></td>
          </tr>
          <tr>
            <td><p style="font-size:8px; margin-top:-5px;"><%= params[:guest_id] %></p></td>
          </tr>
        </tbody>
      </table>
      
      <script>
        setTimeout(function () { window.print(); }, 500);
        window.onfocus = function () { setTimeout(function () { window.close(); }, 500); }
      </script>
        
</body>
</html>

app/views/weddings/update_presence.js.erb
$("#notice").html("<%= escape_javascript(render 'hadir') %>")
window.open("<%= print_weddings_path({:guest_id=>@find_guest.first.guest_id}) %>",'targetWindow','toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=200,height=120');