config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'user/index'

  get 'user/new'

  get 'user/create'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  mount Sidekiq::Web => '/sidekiq'

  scope "/admin" do
    resources :users
  end

  root 'weddings#dashboard'

  resources :events
  resources :settings do
    member do
      put :aktifasi
      patch :customtext
    end
    collection do
      get :reset
    end
  end
  resources :displays
  resources :type_of_events
  resources :guests do
  	collection {
    post :import
    get :presence
    get :transfer
    get :gift
    get :print_qr
    get :print_no_undian
  	}
  end

  resources :weddings do
    collection{
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :report_wedding
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      post :import  
    }
  end

  resources :gatherings do
    collection{
      post :import
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      get :pengaturan
      get :reset
    }
  end

  resources :concerts do
    collection{
      post :import
      get :update_presence
      get :printulang
      get :reprint
      get :update_souvenir
      get :print
      get :print_qr
      get :print_qr_master
      get :template_qr
      get :template_qr_master
      get :report_concert
      get :souvenir
      get :export_excel
      get :print_qr_page
      get :report
      get :dashboard
      get :search
      get :pengaturan
      get :reset
    }
  end

  get '/dashboards/coming_soon', to: 'dashboards#coming_soon'
  get '/dashboards', to: 'dashboards#index'

end

app/models/type_of_event.rb
class TypeOfEvent < ApplicationRecord
	has_many :events
	def self.search(name)
		name = name ? name.upcase : ""
    	where("upper(name) ilike ?", "%#{name}%")
	end
end

app/controllers/type_of_events_controller.rb
class TypeOfEventsController < ApplicationController
  before_action :set_type_of_event, only: [:show, :edit, :update, :destroy]

  # GET /type_of_events
  # GET /type_of_events.json
  def index
    @type_of_events = TypeOfEvent.search(params[:name]).page(params[:page]).per(5)
  end

  # GET /type_of_events/1
  # GET /type_of_events/1.json
  def show
  end

  # GET /type_of_events/new
  def new
    @type_of_event = TypeOfEvent.new
  end

  # GET /type_of_events/1/edit
  def edit
  end

  # POST /type_of_events
  # POST /type_of_events.json
  def create
    @type_of_event = TypeOfEvent.new(type_of_event_params)

    respond_to do |format|
      if @type_of_event.save
        format.html { redirect_to type_of_events_path, notice: 'Type of event was successfully created.' }
        format.json { render :show, status: :created, location: @type_of_event }
      else
        format.html { render :new }
        format.json { render json: @type_of_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_of_events/1
  # PATCH/PUT /type_of_events/1.json
  def update
    respond_to do |format|
      if @type_of_event.update(type_of_event_params)
        format.html { redirect_to type_of_events_url, notice: 'Type of event was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_of_event }
      else
        format.html { render :edit }
        format.json { render json: @type_of_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_of_events/1
  # DELETE /type_of_events/1.json
  def destroy
    @type_of_event.destroy
    respond_to do |format|
      format.html { redirect_to type_of_events_url, notice: 'Type of event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_of_event
      @type_of_event = TypeOfEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_of_event_params
      params.require(:type_of_event).permit(:name)
    end
end

app/helpers/type_of_events_helper.rb
module TypeOfEventsHelper
end

app/views/type_of_events/_form.html.erb
<%= form_with(model: type_of_event, local: true, class: 'form-horizontal') do |form| %>
  <% if type_of_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type_of_event.errors.count, "error") %> prohibited this type_of_event from being saved:</h2>

      <ul>
      <% type_of_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control', type: 'text' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= link_to 'Back', type_of_events_path, class:'btn btn-danger' %>
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/type_of_events/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            Edit Event Type 
        </h3>
    </div>
  <div class="panel-body">
    <%= render 'form', type_of_event: @type_of_event %>
  </div>
</div>

app/views/type_of_events/index.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            Master Event Type
            <%= link_to 'New Event Type', new_type_of_event_path, class: 'btn btn-primary btn-sm pull-right' %>
        </h3>
    </div><br>

    <%= form_tag type_of_events_path, method: "GET" do %>
      <% 5.times do %>
        <div class="col-sm-2"></div>
      <% end %>
      <div class="col-sm-2">
        <%= text_field_tag :name, params[:name], class: "form-control form-control-sm", placeholder: "Search" %>
      </div>
    <% end %><br>

  <div class="panel-body">
    <table id="data-table" class="table table-hovered table-bordered margin10">
        <thead class="thead-default">
            <tr>
                <th>Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <% @type_of_events.each do |type_of_event| %>
            <tr>
                <td><%= type_of_event.name %></td>
                <td>
                    <div class="btn-group" role="group" aria-label="...">
                        <button type="button" class="btn btn-success btn-sm"><%= link_to 'Edit', edit_type_of_event_path(type_of_event) %></button>
                        <button type="button" class="btn btn-delete btn-sm"><%= link_to 'Destroy', type_of_event, method: :delete, data: { confirm: 'Are you sure?' } %></button>
                    </div>
                </td>
            </tr>
            <% end %>

            </tbody>
        </table>
        <%= paginate @type_of_events %>
  </div>


</div>

app/views/type_of_events/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            New Event Type 
        </h3>
    </div>
  <div class="panel-body">
    <%= render 'form', type_of_event: @type_of_event %>
  </div>
</div>

app/views/type_of_events/show.html.erb
<%= link_to 'Edit', edit_type_of_event_path(@type_of_event) %> |
<%= link_to 'Back', type_of_events_path %>